version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Dependabot can update major versions (e.g., v6 -> v7) when using major version tags
