version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ""
    labels:
      - "cc: chore"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ""
    labels:
      - "cc: chore"
